### ISSUE TITLE
There are different positions in the top-left wave

### ISSUE THREAD

**Issue by LoreA-dev** [LoreA-dev/Adoption-WebSite#25]
I think we should fix this. 

![image](https://user-images.githubusercontent.com/69254695/125369408-c60c3400-e341-11eb-9683-f95fa2858361.png)
![image](https://user-images.githubusercontent.com/69254695/125369413-cd334200-e341-11eb-9f89-ee415fb28b44.png)

**Comment by santiago-jv** [comment]
I think that we should remove this header and create another.
